### PR TITLE
Feature/redesign page structure

### PR DESCRIPTION
**Pull request by yagotome**
- Redesign page layout structure to support optional padding (or max-widht) per section
- Support media query within the React Component

### CODE REVIEW

**Comment by yagotome** [comment]
> Dude, it looks great -- but there's one weird problem going on. It seems that babel's helper compilation dependency is failing to do its job.

This sounds strange again. For it keeps working properly. Did you ran `yarn` (for installing dependencies) before building?

> Lastly, can you double-check some of the code formattings? I don't know if it's my WebStorm watcher that is misconfigured or if some of the code is not complying with our pre-defined rules.

I'm not sure about the problem WebStorm pointed out to you, but I've run a `yarn format` to _prettify_ all the source code. Can you check if everything is solved please?

**Comment by yagotome** [comment]
> Dude, it looks great -- but there's one weird problem going on. It seems that babel's helper compilation dependency is failing to do its job.

This sounds really weird, again. For it keeps working properly. Did you ran `yarn` (for installing dependencies) before building?

> Lastly, can you double-check some of the code formattings? I don't know if it's my WebStorm watcher that is misconfigured or if some of the code is not complying with our pre-defined rules.

I'm not sure about the problem WebStorm pointed out to you, but I've run a `yarn format` to _prettify_ all the source code. Can you check if everything is solved please?

**Comment by yagotome** [comment]
> Dude, it looks great -- but there's one weird problem going on. It seems that babel's helper compilation dependency is failing to do its job.

@BelfDev this sounds really weird, again. That keeps working properly for me, lol. Did you ran `yarn` (for installing dependencies) before building?

> Lastly, can you double-check some of the code formattings? I don't know if it's my WebStorm watcher that is misconfigured or if some of the code is not complying with our pre-defined rules.

I'm not sure about the problem WebStorm pointed out to you, but I've run a `yarn format` to _prettify_ all the source code. Can you check if everything is solved please?

**Comment by BelfDev** [comment]
> I'm not sure about the problem WebStorm pointed out to you

I'm sorry if I failed to be clear enough. _WebStorm_ was pointing me out that our code format didn't comply with our pre-defined  **[prettier](https://prettier.io/docs/en/index.html)** set of rules. In my latest post, I segregated which files needed to be _prettified_. Thanks for doing that.

I appreciate you reminding me of [yarn install](https://yarnpkg.com/cli/install), but unfortunately (or not) I have the habit of running it periodically; I can confirm I have run it before reporting the issue here. 

Screen Shot 2020-04-30 at 8 57 10 AM

The problem persists. I followed some of the steps laid out in the aforementioned [issue](https://github.com/babel/babel/issues/11216), but despite managing to narrow down the problem, it remains unsolved.

I have removed my `node_modules` folder along with the `package-lock.json` file (not ideal). I have also cleaned both yarn cache and gatsby cache.

```
yarn clean
yarn cache clean
rm -rf node_modules/ 
rm -rf package-lock.json
yarn install
```

My assumption is that we need to bump up the `@babel/helper-compilation-targets` version. Would you mind looking into that?

**Comment by yagotome** [comment]
> The problem persists. I followed some of the steps laid out in the aforementioned [issue](https://github.com/babel/babel/issues/11216), but despite managing to narrow down the problem, it remains unsolved.
> 
> I have removed my `node_modules` folder along with the `package-lock.json` file (not ideal). I have also cleaned both yarn cache and gatsby cache.
> 
> ```
> yarn clean
> yarn cache clean
> rm -rf node_modules/ 
> rm -rf package-lock.json
> yarn install
> ```
> 
> My assumption is that we need to bump up the `@babel/helper-compilation-targets` version. Would you mind looking into that?

I've done all steps you mentioned from that issue and I still cannot reproduce this error. Could you tell me your node and yarn versions (`node -v` and `yarn -v` respectively)?

**Comment by BelfDev** [comment]
> > The problem persists. I followed some of the steps laid out in the aforementioned [issue](https://github.com/babel/babel/issues/11216), but despite managing to narrow down the problem, it remains unsolved.
> > I have removed my `node_modules` folder along with the `package-lock.json` file (not ideal). I have also cleaned both yarn cache and gatsby cache.
> > ```
> > yarn clean
> > yarn cache clean
> > rm -rf node_modules/ 
> > rm -rf package-lock.json
> > yarn install
> > ```
> > 
> > 
> > My assumption is that we need to bump up the `@babel/helper-compilation-targets` version. Would you mind looking into that?
> 
> I've done all steps you mentioned from that issue and I still cannot reproduce this error. Could you tell me your node and yarn versions (`node -v` and `yarn -v` respectively)?

Yarn version: 1.22.4
Node version: 13.13.0

**Pull request merged**
